version: '3.9'
services:
  db:
    image: postgres:alpine
    container_name: ja-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwer
      POSTGRES_DB: jobapps
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'